# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools/ui_profiletool.ui'
#
# Created: Sat Mar 17 12:08:43 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ui_profiletool(object):
    def setupUi(self, ui_profiletool):
        ui_profiletool.setObjectName(_fromUtf8("ui_profiletool"))
        ui_profiletool.resize(643, 367)
        ui_profiletool.setWindowTitle(QtGui.QApplication.translate("ui_profiletool", "Profile Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.formLayout = QtGui.QFormLayout(self.dockWidgetContents)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridlayout = QtGui.QGridLayout(self.tab)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.scaleSlider = QtGui.QSlider(self.tab)
        self.scaleSlider.setOrientation(QtCore.Qt.Vertical)
        self.scaleSlider.setObjectName(_fromUtf8("scaleSlider"))
        self._2.addWidget(self.scaleSlider)
        self.qwtPlot = QwtPlot(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlot.sizePolicy().hasHeightForWidth())
        self.qwtPlot.setSizePolicy(sizePolicy)
        self.qwtPlot.setAutoFillBackground(False)
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self._2.addWidget(self.qwtPlot)
        self.gridlayout.addLayout(self._2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self._3 = QtGui.QVBoxLayout(self.tab_2)
        self._3.setObjectName(_fromUtf8("_3"))
        self._4 = QtGui.QHBoxLayout()
        self._4.setObjectName(_fromUtf8("_4"))
        self.statBox1 = QtGui.QGroupBox(self.tab_2)
        self.statBox1.setTitle(QtGui.QApplication.translate("ui_profiletool", "Profile 1", None, QtGui.QApplication.UnicodeUTF8))
        self.statBox1.setObjectName(_fromUtf8("statBox1"))
        self._5 = QtGui.QGridLayout(self.statBox1)
        self._5.setObjectName(_fromUtf8("_5"))
        self.stat1 = QtGui.QLabel(self.statBox1)
        self.stat1.setText(QtGui.QApplication.translate("ui_profiletool", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.stat1.setTextFormat(QtCore.Qt.AutoText)
        self.stat1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.stat1.setWordWrap(True)
        self.stat1.setObjectName(_fromUtf8("stat1"))
        self._5.addWidget(self.stat1, 0, 0, 1, 1)
        self._4.addWidget(self.statBox1)
        self.statBox2 = QtGui.QGroupBox(self.tab_2)
        self.statBox2.setTitle(QtGui.QApplication.translate("ui_profiletool", "Profile 2", None, QtGui.QApplication.UnicodeUTF8))
        self.statBox2.setObjectName(_fromUtf8("statBox2"))
        self._6 = QtGui.QGridLayout(self.statBox2)
        self._6.setObjectName(_fromUtf8("_6"))
        self.stat2 = QtGui.QLabel(self.statBox2)
        self.stat2.setText(QtGui.QApplication.translate("ui_profiletool", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.stat2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.stat2.setWordWrap(True)
        self.stat2.setObjectName(_fromUtf8("stat2"))
        self._6.addWidget(self.stat2, 0, 0, 1, 1)
        self._4.addWidget(self.statBox2)
        self.statBox3 = QtGui.QGroupBox(self.tab_2)
        self.statBox3.setTitle(QtGui.QApplication.translate("ui_profiletool", "Profile 3", None, QtGui.QApplication.UnicodeUTF8))
        self.statBox3.setObjectName(_fromUtf8("statBox3"))
        self._7 = QtGui.QGridLayout(self.statBox3)
        self._7.setObjectName(_fromUtf8("_7"))
        self.stat3 = QtGui.QLabel(self.statBox3)
        self.stat3.setText(QtGui.QApplication.translate("ui_profiletool", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.stat3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.stat3.setWordWrap(True)
        self.stat3.setObjectName(_fromUtf8("stat3"))
        self._7.addWidget(self.stat3, 0, 0, 1, 1)
        self._4.addWidget(self.statBox3)
        self._3.addLayout(self._4)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setTitle(QtGui.QApplication.translate("ui_profiletool", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self._8 = QtGui.QGridLayout(self.groupBox)
        self._8.setObjectName(_fromUtf8("_8"))
        self.stats = QtGui.QLabel(self.groupBox)
        self.stats.setText(QtGui.QApplication.translate("ui_profiletool", "Start\n"
"Stop\n"
"Length", None, QtGui.QApplication.UnicodeUTF8))
        self.stats.setTextFormat(QtCore.Qt.AutoText)
        self.stats.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.stats.setWordWrap(True)
        self.stats.setObjectName(_fromUtf8("stats"))
        self._8.addWidget(self.stats, 0, 0, 1, 1)
        self._3.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self._9 = QtGui.QGridLayout(self.tab_4)
        self._9.setObjectName(_fromUtf8("_9"))
        self._10 = QtGui.QHBoxLayout()
        self._10.setObjectName(_fromUtf8("_10"))
        self._11 = QtGui.QVBoxLayout()
        self._11.setObjectName(_fromUtf8("_11"))
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setText(QtGui.QApplication.translate("ui_profiletool", "Profile 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self._11.addWidget(self.label_23)
        self.setLayer1 = QtGui.QComboBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setLayer1.sizePolicy().hasHeightForWidth())
        self.setLayer1.setSizePolicy(sizePolicy)
        self.setLayer1.setObjectName(_fromUtf8("setLayer1"))
        self._11.addWidget(self.setLayer1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._11.addItem(spacerItem)
        self._10.addLayout(self._11)
        self._12 = QtGui.QHBoxLayout()
        self._12.setObjectName(_fromUtf8("_12"))
        self._13 = QtGui.QVBoxLayout()
        self._13.setObjectName(_fromUtf8("_13"))
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setText(QtGui.QApplication.translate("ui_profiletool", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self._13.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setText(QtGui.QApplication.translate("ui_profiletool", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self._13.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setText(QtGui.QApplication.translate("ui_profiletool", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self._13.addWidget(self.label_26)
        self._12.addLayout(self._13)
        self._14 = QtGui.QVBoxLayout()
        self._14.setObjectName(_fromUtf8("_14"))
        self.setR1 = QtGui.QSlider(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setR1.sizePolicy().hasHeightForWidth())
        self.setR1.setSizePolicy(sizePolicy)
        self.setR1.setMinimumSize(QtCore.QSize(35, 0))
        self.setR1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setR1.setOrientation(QtCore.Qt.Horizontal)
        self.setR1.setObjectName(_fromUtf8("setR1"))
        self._14.addWidget(self.setR1)
        self.setG1 = QtGui.QSlider(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setG1.sizePolicy().hasHeightForWidth())
        self.setG1.setSizePolicy(sizePolicy)
        self.setG1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setG1.setOrientation(QtCore.Qt.Horizontal)
        self.setG1.setObjectName(_fromUtf8("setG1"))
        self._14.addWidget(self.setG1)
        self.setB1 = QtGui.QSlider(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setB1.sizePolicy().hasHeightForWidth())
        self.setB1.setSizePolicy(sizePolicy)
        self.setB1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setB1.setOrientation(QtCore.Qt.Horizontal)
        self.setB1.setObjectName(_fromUtf8("setB1"))
        self._14.addWidget(self.setB1)
        self._12.addLayout(self._14)
        self.colorBox1 = QtGui.QGraphicsView(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorBox1.sizePolicy().hasHeightForWidth())
        self.colorBox1.setSizePolicy(sizePolicy)
        self.colorBox1.setMaximumSize(QtCore.QSize(50, 50))
        self.colorBox1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.colorBox1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.colorBox1.setAcceptDrops(False)
        self.colorBox1.setAutoFillBackground(True)
        self.colorBox1.setInteractive(False)
        self.colorBox1.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.colorBox1.setViewportUpdateMode(QtGui.QGraphicsView.FullViewportUpdate)
        self.colorBox1.setOptimizationFlags(QtGui.QGraphicsView.DontClipPainter)
        self.colorBox1.setObjectName(_fromUtf8("colorBox1"))
        self._12.addWidget(self.colorBox1)
        self._10.addLayout(self._12)
        self._9.addLayout(self._10, 0, 0, 1, 1)
        self._15 = QtGui.QHBoxLayout()
        self._15.setObjectName(_fromUtf8("_15"))
        self._16 = QtGui.QVBoxLayout()
        self._16.setObjectName(_fromUtf8("_16"))
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setText(QtGui.QApplication.translate("ui_profiletool", "Profile 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self._16.addWidget(self.label_28)
        self.setLayer2 = QtGui.QComboBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setLayer2.sizePolicy().hasHeightForWidth())
        self.setLayer2.setSizePolicy(sizePolicy)
        self.setLayer2.setObjectName(_fromUtf8("setLayer2"))
        self._16.addWidget(self.setLayer2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._16.addItem(spacerItem1)
        self._15.addLayout(self._16)
        self._17 = QtGui.QHBoxLayout()
        self._17.setObjectName(_fromUtf8("_17"))
        self._18 = QtGui.QVBoxLayout()
        self._18.setObjectName(_fromUtf8("_18"))
        self.label_29 = QtGui.QLabel(self.tab_4)
        self.label_29.setText(QtGui.QApplication.translate("ui_profiletool", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self._18.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(self.tab_4)
        self.label_30.setText(QtGui.QApplication.translate("ui_profiletool", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self._18.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.tab_4)
        self.label_31.setText(QtGui.QApplication.translate("ui_profiletool", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self._18.addWidget(self.label_31)
        self._17.addLayout(self._18)
        self._19 = QtGui.QVBoxLayout()
        self._19.setObjectName(_fromUtf8("_19"))
        self.setR2 = QtGui.QSlider(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setR2.sizePolicy().hasHeightForWidth())
        self.setR2.setSizePolicy(sizePolicy)
        self.setR2.setMinimumSize(QtCore.QSize(35, 0))
        self.setR2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setR2.setOrientation(QtCore.Qt.Horizontal)
        self.setR2.setObjectName(_fromUtf8("setR2"))
        self._19.addWidget(self.setR2)
        self.setG2 = QtGui.QSlider(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setG2.sizePolicy().hasHeightForWidth())
        self.setG2.setSizePolicy(sizePolicy)
        self.setG2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setG2.setOrientation(QtCore.Qt.Horizontal)
        self.setG2.setObjectName(_fromUtf8("setG2"))
        self._19.addWidget(self.setG2)
        self.setB2 = QtGui.QSlider(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setB2.sizePolicy().hasHeightForWidth())
        self.setB2.setSizePolicy(sizePolicy)
        self.setB2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setB2.setOrientation(QtCore.Qt.Horizontal)
        self.setB2.setObjectName(_fromUtf8("setB2"))
        self._19.addWidget(self.setB2)
        self._17.addLayout(self._19)
        self.colorBox2 = QtGui.QGraphicsView(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorBox2.sizePolicy().hasHeightForWidth())
        self.colorBox2.setSizePolicy(sizePolicy)
        self.colorBox2.setMaximumSize(QtCore.QSize(50, 50))
        self.colorBox2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.colorBox2.setAcceptDrops(False)
        self.colorBox2.setObjectName(_fromUtf8("colorBox2"))
        self._17.addWidget(self.colorBox2)
        self._15.addLayout(self._17)
        self._9.addLayout(self._15, 1, 0, 1, 1)
        self._20 = QtGui.QHBoxLayout()
        self._20.setObjectName(_fromUtf8("_20"))
        self._21 = QtGui.QVBoxLayout()
        self._21.setObjectName(_fromUtf8("_21"))
        self.label_32 = QtGui.QLabel(self.tab_4)
        self.label_32.setText(QtGui.QApplication.translate("ui_profiletool", "Profile 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self._21.addWidget(self.label_32)
        self.setLayer3 = QtGui.QComboBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setLayer3.sizePolicy().hasHeightForWidth())
        self.setLayer3.setSizePolicy(sizePolicy)
        self.setLayer3.setObjectName(_fromUtf8("setLayer3"))
        self._21.addWidget(self.setLayer3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._21.addItem(spacerItem2)
        self._20.addLayout(self._21)
        self._22 = QtGui.QHBoxLayout()
        self._22.setObjectName(_fromUtf8("_22"))
        self._23 = QtGui.QVBoxLayout()
        self._23.setObjectName(_fromUtf8("_23"))
        self.label_33 = QtGui.QLabel(self.tab_4)
        self.label_33.setText(QtGui.QApplication.translate("ui_profiletool", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self._23.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.tab_4)
        self.label_34.setText(QtGui.QApplication.translate("ui_profiletool", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self._23.addWidget(self.label_34)
        self.label_35 = QtGui.QLabel(self.tab_4)
        self.label_35.setText(QtGui.QApplication.translate("ui_profiletool", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self._23.addWidget(self.label_35)
        self._22.addLayout(self._23)
        self._24 = QtGui.QVBoxLayout()
        self._24.setObjectName(_fromUtf8("_24"))
        self.setR3 = QtGui.QSlider(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setR3.sizePolicy().hasHeightForWidth())
        self.setR3.setSizePolicy(sizePolicy)
        self.setR3.setMinimumSize(QtCore.QSize(35, 0))
        self.setR3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setR3.setOrientation(QtCore.Qt.Horizontal)
        self.setR3.setObjectName(_fromUtf8("setR3"))
        self._24.addWidget(self.setR3)
        self.setG3 = QtGui.QSlider(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setG3.sizePolicy().hasHeightForWidth())
        self.setG3.setSizePolicy(sizePolicy)
        self.setG3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setG3.setOrientation(QtCore.Qt.Horizontal)
        self.setG3.setObjectName(_fromUtf8("setG3"))
        self._24.addWidget(self.setG3)
        self.setB3 = QtGui.QSlider(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setB3.sizePolicy().hasHeightForWidth())
        self.setB3.setSizePolicy(sizePolicy)
        self.setB3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setB3.setOrientation(QtCore.Qt.Horizontal)
        self.setB3.setObjectName(_fromUtf8("setB3"))
        self._24.addWidget(self.setB3)
        self._22.addLayout(self._24)
        self.colorBox3 = QtGui.QGraphicsView(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorBox3.sizePolicy().hasHeightForWidth())
        self.colorBox3.setSizePolicy(sizePolicy)
        self.colorBox3.setMaximumSize(QtCore.QSize(50, 50))
        self.colorBox3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.colorBox3.setAcceptDrops(False)
        self.colorBox3.setObjectName(_fromUtf8("colorBox3"))
        self._22.addWidget(self.colorBox3)
        self._20.addLayout(self._22)
        self._9.addLayout(self._20, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self._25 = QtGui.QGridLayout(self.tab_3)
        self._25.setObjectName(_fromUtf8("_25"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setText(QtGui.QApplication.translate("ui_profiletool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Profile Tool Plugin</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The Profile Plugin plots terrain profiles along interactive pointed polylines. It handles  any format supported by QGis. You can compare up to three layers together, control height scale and line colors. Unfortunately it has huge requirements: development version of QGIS and Qwt5.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please send me your reflections, opinions, suggestions and wishes (especially related to this plugin;) on <a href=\"http://hub.qgis.org/projects/profiletool/issues\"><span style=\" text-decoration: underline; color:#0000ff;\">http://hub.qgis.org/projects/profiletool/issues</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you find this plugin useful please don\'t hesitate to let me know desired improvements!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Profile Tool Plugin - License GNU GPL 2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Written in 2008 by Borys Jurgiel (borys@wolf.most.org.pl)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Written in 2012 by Borys Jurgiel, Patrice Verchere</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">REQUIREMENTS:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Qwt5 (python-qwt5-qt4)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- QT ver 4.1 for saving to PDF and 4.3 for saving to SVG</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self._25.addWidget(self.label_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.tabWidget)
        self._26 = QtGui.QHBoxLayout()
        self._26.setObjectName(_fromUtf8("_26"))
        spacerItem3 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self._26.addItem(spacerItem3)
        self.butPrint = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butPrint.sizePolicy().hasHeightForWidth())
        self.butPrint.setSizePolicy(sizePolicy)
        self.butPrint.setMinimumSize(QtCore.QSize(100, 0))
        self.butPrint.setText(QtGui.QApplication.translate("ui_profiletool", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.butPrint.setObjectName(_fromUtf8("butPrint"))
        self._26.addWidget(self.butPrint)
        self.butPDF = QtGui.QPushButton(self.dockWidgetContents)
        self.butPDF.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butPDF.sizePolicy().hasHeightForWidth())
        self.butPDF.setSizePolicy(sizePolicy)
        self.butPDF.setMinimumSize(QtCore.QSize(100, 0))
        self.butPDF.setText(QtGui.QApplication.translate("ui_profiletool", "Save as PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.butPDF.setObjectName(_fromUtf8("butPDF"))
        self._26.addWidget(self.butPDF)
        self.butSVG = QtGui.QPushButton(self.dockWidgetContents)
        self.butSVG.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butSVG.sizePolicy().hasHeightForWidth())
        self.butSVG.setSizePolicy(sizePolicy)
        self.butSVG.setMinimumSize(QtCore.QSize(100, 0))
        self.butSVG.setText(QtGui.QApplication.translate("ui_profiletool", "Save as SVG", None, QtGui.QApplication.UnicodeUTF8))
        self.butSVG.setObjectName(_fromUtf8("butSVG"))
        self._26.addWidget(self.butSVG)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._26.addItem(spacerItem4)
        self.buttonBox = QtGui.QDialogButtonBox(self.dockWidgetContents)
        self.buttonBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self._26.addWidget(self.buttonBox)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self._26)
        ui_profiletool.setWidget(self.dockWidgetContents)

        self.retranslateUi(ui_profiletool)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ui_profiletool)

    def retranslateUi(self, ui_profiletool):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ui_profiletool", "&Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ui_profiletool", "&Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("ui_profiletool", "S&etup", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ui_profiletool", "&About", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4.Qwt5 import QwtPlot
